//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anofoods.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public long Id { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public string Type { get; set; }
        public System.Guid MasterId { get; set; }
        public string Owned { get; set; }
    }
}
